### ISSUE TITLE
Unable to enable push notifications

### ISSUE THREAD

**Issue by joshmatta** [pusher/chatkit-android#105]
When calling
```kotlin
currentUser.enablePushNotifications { result ->
              when(result) {
                  is Result.Success -> Log.i("Success", "Push Notifications enabled")
                  else -> Log.e("Error", "Error starting Push Notifications")
              }
          }
```
As mentioned [here](https://docs.pusher.com/chatkit/push_notifications/setup-android#enable-push-notifications) in docs

Neither of the above messages are displayed in the log. So, basically callback function is not being called by the sdk. Please let me know if it is a bug with the sdk or I implemented it wrong.

**Comment by freddie1129** [comment]
I have the same issue with you today. Did you resolve it?

**Comment by joshmatta** [comment]
Nope, used another alternative

**Comment by freddie1129** [comment]
After two days' struggle, I think we can never enable the notification feature by following their document. 
By tracking the source code, I finally found currently what we can do is setting a Context when initializing the `AndroidChatkitDependencies`, then the notification can be enabled. You cannot find any words about it in their document.  The constructor of `AndroidChatkitDependencies` is also not easy for Java developer. They should update their code and documentation. It is so confusing.

The other issue related to Notification that you cannot receive any notifications when App is running in the foreground. As I know, Chatkit notification feature is built based on the Firebase Message Service. Technically, we should be able to handle the notification which is coming when App is running in the foreground by a `FirebaseMessagingService`. Unfortunately, once you add the Chatkit SDK into your project,  `FirebaseMessagingService` cannot work anymore.  It is proved in an empty testing project which only includes Chatkit SDK and without any Chatkit code.

**Comment by luismfonseca** [comment]
> The constructor of AndroidChatkitDependencies is also not easy for Java developer. They should update their code and documentation. It is so confusing.

This is a good point, we will need to improve this at some point.

> The other issue related to Notification that you cannot receive any notifications when App is running in the foreground.

Chatkit SDK uses Beams internally, so the docs for how to do this are [here](https://pusher.com/docs/beams/guides/handle-incoming-notifications#handle-all-notifications). However, I'm not sure you'd need to do this as you should also be receiving this information directly via the Chatkit subscriptions. Or maybe there's something I'm missing!

**Comment by joshmatta** [comment]
> Unfortunately, once you add the Chatkit SDK into your project, FirebaseMessagingService cannot work anymore.

You can give your custom FirebaseMessagingService a higher priority. Chatkit has set its priority to 1 so you can assign a higher value to your service and then you override it.

```xml
        <service
            android:name=".service.MyFirebaseMessagingService">
            <intent-filter android:priority="100">
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

**Comment by mdpye** [comment]
Thanks for the report. I'm updating the documentation now, it does seems to have been overlooked to call it out properly as a requirement.

@joshmatta it's also a bug that exceptions raised during a call (which are rare, but is how the lack of a `Context` would be communicated to you as an error) don't get captured and wrapped in errors when you use the callback interface. There will be a release to resolve that soon.

Sorry for the inconveniences.

**Comment by mdpye** [comment]
1.3.3 has been released, which should pass back the error correctly (telling you that a context is required to enable push notifications).

I've also updated the docs.
