### ISSUE TITLE
Some function is missing in chatkit version 1.2.0 

### ISSUE THREAD

**Issue by vivekshaw** [pusher/chatkit-android#107]
Some functions is missing in chatkit version 1.2.0 like 
var cursorResult = currentUser.getReadCursor("lobby", otherUserId)
when (cursorResult) {
  is Result.Success -> /* cursorResult.value... */
}

currentUser.subscribeToRoomMultipart(
  roomId = "lobby",
  listeners = RoomListeners(
    onNewReadCursor = { cursor ->
      // e.g. toast("User ${cursor.user.name} has read up to message ${cursor.position}")
    }
  ),
  callback = { /* ... */ }
)

You can find your library code from GitHub and check that function ..You can not find because it is not available . Please make proper document after proper release of your library .

**Comment by daniellevass** [comment]
Hi, closing this issue as there has not been any activity in some time. If this is still an issue please contact support@pusher.com, and they can give you more direct help 🙂
