### ISSUE TITLE
Can not use chatbeem library 1.4.0 with chatkit version 1.2.0 in android 

### ISSUE THREAD

**Issue by vivekshaw** [pusher/chatkit-android#108]
Since your latest chatkit android library version is 1.2.0 and your latest chatbeem library is 1.4.0 ..I can not build grade because chatkit library also contains push notifications code ..so getting duplicate class error in grade build .even enable Pushnotification in chatkit is not working .
Please make proper library before release .For Android your documention is not matching with your latest chatkit library 1.2.0 ..

**Comment by daniellevass** [comment]
Hi, closing this issue as there has not been any activity in some time. If this is still an issue please contact support@pusher.com, and they can give you more direct help 🙂
