### ISSUE TITLE
ChatListeners cannot be fired after setting a read cursor 

### ISSUE THREAD

**Issue by freddie1129** [pusher/chatkit-android#113]
My App has two views. The first one is a Room List View. When app user clicks one of the rooms, a Chat View will be opened. I need to monitor the changes of unReadCount on the Room List View via a ChatListeners for every room. 
Everything looks fine before I set a read cursor in the Chat view.  The onRoomUpdated callback on in the ChatListerner will be fired when a messaging is coming, so I can get the latest unreadCount in it. Unfortunately,  after I set a Read Cursor in the Chat View, the Chatlistener won't be triggered any more. I  can confirm that the Read Cursor is set successfully because the value of unReadCount is changed when I restart the app.  
Thank you.

**Comment by daniellevass** [comment]
Thanks for raising this issue! We've released a fix in `1.8.1` so if you update your dependency you shouldn't see this issue again! I'm closing this issue out but please re-open if you're still experiencing issues 😃
