### ISSUE TITLE
multiPart messages API not avail in 1.3.1 ; also cant send or receive messages

### ISSUE THREAD

**Issue by SogoGolf** [pusher/chatkit-android#114]
we had no troubles getting started with the iOS SDK which is great. however not so much luck with Android SDK.

We're on minSDKVersion 23 & targetSdkVersion 28. Android Studio 3.3.2. This is a Kotlin based Android app.

__gradle entry__
```implementation 'com.pusher:chatkit-android:1.3.1'```

Connecting is fine and works.

"currentUser" is defined as a class level var.
```private lateinit var currentUser: CurrentUser```

_Subscribing seems to have API problems:_

There a no methods available for "subscribeToRoomMultipart(...). Only "subscribeToRoom" shows up. 
![image](https://user-images.githubusercontent.com/19580787/57125926-90b54480-6dce-11e9-9932-e3eb5531e2a1.png)

We tried the "subscribeToRoom" which compiled ok, but the error callback was returning this:-

```Failed to extract required url params```

This is our initialisation block:
```
 chatManager = ChatManager(
                instanceLocator = "v1:usxxxxxxxxxxxxxxx",
                userId = "abc@xyz.golf",
                dependencies = AndroidChatkitDependencies(
                        tokenProvider = ChatkitTokenProvider(
                                endpoint = "https://xxxxxxxxxxxxxx/token",
                                userId = "abc@xyz.golf"
                        )
                )
        )
```

Is something set incorrectly in the init function ?

Also just for reference following is the subscribeToRoom function:
```
currentUser.subscribeToRoom(
    roomId = "comps",
    listeners = RoomListeners(
            onMessage = {
                Log.i("CHAT234", "message is ${it.text}")
            },
            onMultipartMessage = {
                Log.i("CHAT234", "message sender is ${it.sender.id}")
            },
            onUserStartedTyping = {
                Log.i("CHAT234", "user started typing: ${it.id}")
            },
            onErrorOccurred = {
                Log.i("CHAT234", "ERROR is ${it.reason}")
            }

    ),
    messageLimit = 20,
    callback = {subscription ->
        Log.i("CHAT234", "subscrip callback..")
        Log.i("CHAT234", "is subscribed ? ${currentUser.isSubscribedToRoom("sogo_comps")}")
```

We couldn't really do much by this point so have raised this ticket. Appreciate if you can look at this.

**Comment by SogoGolf** [comment]
ok first bit is sorted which was using the teeny tiny id number underneath the room name in the ChatKit "Console" . Would be great if you can document that better!

![image](https://user-images.githubusercontent.com/19580787/57127190-ec81cc80-6dd2-11e9-90bf-76c45785a1f2.png)

This got the subscription working (we can receive chat messages).

**Comment by freddie1129** [comment]
They have fixed the _**subscribeToRoomMultipart**_ issue last night.

**Comment by SogoGolf** [comment]
great thanks! will give it a try today

**Comment by SogoGolf** [comment]
works perfectly thanks very much for the quick turnaround!

**Comment by SogoGolf** [comment]
sorry folks one question on this - for the multipart messages, the payload is of type ```Payload```

how can we access/cast the string of the actual message ? 

eg. ```it.parts[0].payload``` has no properties such as "message"
