### ISSUE TITLE
Gradle ERROR: Failed to resolve: chatkit-parent:pusher-platform-android:unspecified

### ISSUE THREAD

**Issue by spiritinlife** [pusher/chatkit-android#121]
Gradle fails for v1.4.0 and v1.5.0 with this error
ERROR: Failed to resolve: chatkit-parent:pusher-platform-android:unspecified

For v1.3.4 gradle succeeds.

Could be related #43 🤷‍♂

**Comment by adawoud** [comment]
I'm having the same issue as well.

**Comment by jesusdanielx15** [comment]
same issue here with     implementation "com.pusher:chatkit-android:1.5.0"

im having this:

ERROR: Failed to resolve: chatkit-parent:pusher-platform-android:unspecified

**Comment by Parmakli** [comment]
Same issue

**Comment by Parmakli** [comment]
Upgrade to v1.6.0, it builds fine

**Comment by jesusdanielx15** [comment]
yes it worked! thank you.

**Comment by daniellevass** [comment]
Hi. There was an issue with our release process however this was rectified in 1.6.0 as per our [changelog](https://github.com/pusher/chatkit-android/blob/master/CHANGELOG.md). If this is still an issue please contact support@pusher.com, and they can give you more direct help 🙂
