### ISSUE TITLE
listeners of the room don't fire after onReadCursor

### ISSUE THREAD

**Issue by eugenCodreanu** [pusher/chatkit-android#131]
Hi. I have implemented pusher chatkit on IOS and android.
On android (kotlin) I connected to chat and receive the currentUser. Setup chat listener's.
That I observe that listeners works perfectly until I use currentUser.setReadCursor function.
After this it set the cursor but chat listener's don't fire anymore :(
Witch can be the issue? Can you check this.Thanks

**Comment by freddie1129** [comment]
I raised the same issue several months ago but no response. I had to reinitiate chatkit after setReadCursor to reenable the listener.

**Comment by daniellevass** [comment]
Thanks both for raising this issue! We've released a fix in `1.8.1` so if you update your dependency you shouldn't see this issue again! I'm closing this issue out but please re-open if you're still experiencing issues 😃
