### ISSUE TITLE
D/ChatRoomsActivity: error.reason: Room membership required

### ISSUE THREAD

**Issue by maltezc** [pusher/chatkit-android#147]
Hello, I'm trying to integrate Chatkit into my android app however I'm running into issues with a user who is already a member of the room, cannot subscribe to a room and am getting the error: `D/ChatRoomsActivity:error.reason: Room membership required`

The issue is also [here on StackOverflow](https://stackoverflow.com/questions/59771313/pusher-chatkit-android-get-status-readout-of-specified-room)

This happens at the `ChatRoomActivity` once a room as been clicked on from the `ChatRoomListActivity`

Here is the code block being used:

```
currentUser.subscribeToRoomMultipart(
                roomId = roomId,
                listeners = RoomListeners(
                        onMultipartMessage = { message ->
                            Log.d("TAG",message.toString())
                            runOnUiThread(Runnable{
                                adapter.addMessage(message)
                                recycler_view.layoutManager?.scrollToPosition(adapter.itemCount -1)
                            })
                        },
                        onErrorOccurred = { error ->
                            Log.d(AppActivityTags.chatRoomActivityTAG, "error.reason: " + error.reason)
                        }
                ),
                messageLimit = 100, // Optional
                callback = { subscription ->
                    // Called when the subscription has started.
                    // You should terminate the subscription with subscription.unsubscribe()
                    // when it is no longer needed
                }
        )
```

username is: `username2-PCKid`
here is a snippet of dashboard:
Also, although it says `Room membership required`, I am somehow still able to add messages to the room? That is misleading.

<img width="948" alt="Screen Shot 2020-01-16 at 9 04 33 PM" src="https://user-images.githubusercontent.com/12634214/72585711-dc981300-38a3-11ea-851d-78929f60848b.png">

<img width="670" alt="Screen Shot 2020-01-16 at 10 14 17 PM" src="https://user-images.githubusercontent.com/12634214/72588580-a364a080-38ad-11ea-82a9-f2aebe65146b.png">

Any and all help is appreciated!

**Comment by daniellevass** [comment]
Hi, 

I've responded to your question on the stackoverflow post - https://stackoverflow.com/questions/59771313/pusher-chatkit-android-get-status-readout-of-specified-room - figured it'll be easier to keep the conversation in one place  😎
