### ISSUE TITLE
the documents are not matching with version id?

### ISSUE THREAD

**Issue by Iamasthme** [pusher/chatkit-android#34]
currentUser.fetchMessages(
  room = someRoom,
  initialId = 42, // Optional
  direction = NEWER_FIRST, // Optional, OLDER_FIRST by default
  limit = 20 // Optional, 10 by default
).wait().let { result -> 
  when(result) { // Result<List<Message>, Error>
    is Result.Success -> toast("Mesages ${result.value} received.")
    is Result.Failure -> toast("Oops, something bad happened: ${result.error}")
  }
}

i was trying to use Fetch Messages , it was not showing the latest build 0.10.0. can you please update the version?

**Comment by pablisco** [comment]
We have released `0.2.0` which matches the documentation
