### ISSUE TITLE
when we don't specify the initial id, the order is working in vice versa

### ISSUE THREAD

**Issue by Iamasthme** [pusher/chatkit-android#39]
For the first time when i try fetch , Direction.ORDER_FIRST fetch recent twenty messages and DIRECTION.NEWER_FIRST fetch last 20 items and if we specify it's working fine but need to reverse the list to get it done...

**Comment by pablisco** [comment]
This is a presentation concern. You can invert the order when using a `RecyclerView`: https://developer.android.com/reference/android/support/v7/widget/LinearLayoutManager.html#setReverseLayout(boolean)
