### ISSUE TITLE
fetch messages  have random behaviour

### ISSUE THREAD

**Issue by Iamasthme** [pusher/chatkit-android#40]
when i try to fetch first time   i use this fuction 

> fetchMessages(roomId=roomId,direction = Direction.ORDER_FIRST,limit = 20)
and i am listing the id here
05-16 18:32:02.778 26511-27514/1g 1: message item id first time: 1532585  and text fourty
05-16 18:32:02.778 26511-27514/1g 1: message item id first time: 1532584  and text thity nine
05-16 18:32:02.778 26511-27514/1g 1: message item id first time: 1532581  and text thirty six
05-16 18:32:02.778 26511-27514/1g 1: message item id first time: 1532577  and text thirty five
05-16 18:32:02.778 26511-27514/1g 1: message item id first time: 1532575  and text 34
05-16 18:32:02.778 26511-27514/1g 1: message item id first time: 1532574  and text 33
05-16 18:32:02.778 26511-27514/1g 1: message item id first time: 1532573  and text 32
05-16 18:32:02.778 26511-27514/1g 1: message item id first time: 1532571  and text 31
05-16 18:32:02.778 26511-27514/1g 1: message item id first time: 1532569  and text 30
05-16 18:32:02.779 26511-27514/1g 1: message item id first time: 1532568  and text 29
05-16 18:32:02.779 26511-27514/1g 1: message item id first time: 1532567  and text 28
05-16 18:32:02.779 26511-27514/1g 1: message item id first time: 1532566  and text 27
05-16 18:32:02.779 26511-27514/1g 1: message item id first time: 1532563  and text 26
05-16 18:32:02.779 26511-27514/1g 1: message item id first time: 1532562  and text 25
05-16 18:32:02.779 26511-27514/1g 1: message item id first time: 1532561  and text 24
05-16 18:32:02.779 26511-27514/1g 1: message item id first time: 1532560  and text 23
05-16 18:32:02.779 26511-27514/1g 1: message item id first time: 1532559  and text 22
05-16 18:32:02.779 26511-27514/1g 1: message item id first time: 1532558  and text 21
05-16 18:32:02.779 26511-27514/g 1: message item id first time: 1532557  and text 20
05-16 18:32:02.779 26511-27514/1g 1: message item id first time: 1532556  and text 19

> 
and next time i am trying to fetch i am using this
fetchMessages(roomId=room!!.id,initialId = messageItemlast.id,direction = Direction.NEWER_FIRST,limit = 20)
> 05-16 18:42:54.218 32350-32350/1 id for loop inside load  more : 1532514  and text vhj
05-16 18:42:54.218 32350-32350/1 id for loop inside load  more : 1532535  and text second
05-16 18:42:54.218 32350-32350/1 id for loop inside load  more : 1532536  and text third
05-16 18:42:54.218 32350-32350/1 id for loop inside load  more : 1532537  and text fourth
05-16 18:42:54.219 32350-32350/1 id for loop inside load  more : 1532538  and text fifith
05-16 18:42:54.219 32350-32350/1 id for loop inside load  more : 1532539  and text second
05-16 18:42:54.219 32350-32350/1 id for loop inside load  more : 1532542  and text seventh
05-16 18:42:54.219 32350-32350/1 id for loop inside load  more : 1532543  and text eight
05-16 18:42:54.219 32350-32350/1 id for loop inside load  more : 1532544  and text nine
05-16 18:42:54.220 32350-32350/1 id for loop inside load  more : 1532545  and text ten
05-16 18:42:54.220 32350-32350/1 id for loop inside load  more : 1532546  and text 11
05-16 18:42:54.220 32350-32350/1 id for loop inside load  more : 1532547  and text 12
05-16 18:42:54.220 32350-32350/1 id for loop inside load  more : 1532548  and text thirteen
05-16 18:42:54.220 32350-32350/1 id for loop inside load  more : 1532549  and text fourteen
05-16 18:42:54.220 32350-32350/1 id for loop inside load  more : 1532550  and text fifteen
05-16 18:42:54.221 32350-32350/1 id for loop inside load  more : 1532551  and text sixteen
05-16 18:42:54.221 32350-32350/1 id for loop inside load  more : 1532553  and text 17
05-16 18:42:54.221 32350-32350/1 id for loop inside load  more : 1532555  and text 18
05-16 18:42:54.221 32350-32350/1 id for loop inside load  more : 1532556  and text 19
05-16 18:42:54.221 32350-32350/1 id for loop inside load  more : 1532557  and text 20

as you could see the message id 1532557,1532556 should not be fetched..

**Comment by KingIdee** [comment]
This has not been attended to? I face it too.

**Comment by hamchapman** [comment]
The latest release, `0.2.1`, should have fixed this

**Comment by hamchapman** [comment]
Closing as `0.2.1` should have fixed this
