### ISSUE TITLE
need a boolean variable if the message list reached on top and no more items to fetch?

### ISSUE THREAD

**Issue by Iamasthme** [pusher/chatkit-android#44]
For better pagination, api has to give when list is ended. so that app does not need to make api calls anymore

**Comment by hamchapman** [comment]
You can check if the number of items returned is equal to the number requested. If it is you know that there's potentially more messages to fetch. If it's not then you know you've fetched as many as you can.

**Comment by daniellevass** [comment]
Hi, closing this issue as there has not been any activity in some time. If this is still an issue please contact support@pusher.com, and they can give you more direct help 🙂
