### ISSUE TITLE
roomSubscriptionListener is not working  after network connection changes

### ISSUE THREAD

**Issue by Iamasthme** [pusher/chatkit-android#55]
Room Connection Listener is not working when mobile network connection changes go to online-offline-online..
so messages,presence, typing status are not updating..

**Comment by callum-oakley** [comment]
Do you get any errors or anything? Or the events just never arrive?

**Comment by sergiupuhalschi** [comment]
Hi there, I've encountered the same issue. 

The events just never arrive when the network connection changes from offline to online. Should I implement the connectivity listener myself and re-subscribe to the events or it's going to be supported on your end?

Thanks!

**Comment by daniellevass** [comment]
Hi, I believe we fixed this with [1.8.1](https://github.com/pusher/chatkit-android/releases/tag/1.8.1).  If this is still an issue please contact support@pusher.com, and they can give you more direct help 🙂
