### ISSUE TITLE
room Subscription Listener is not subscribing on used typed event?

### ISSUE THREAD

**Issue by Iamasthme** [pusher/chatkit-android#56]
when user started typing , it triggers `onUserStartedTyping` event, but when user stopped typing , its not triggering `onUserStoppedTyping`  event .Please check this

**Comment by callum-oakley** [comment]
Hmmm, you should receive the user stopped  typing event 1500ms after the last user typing event. Can I see the code you are using to:

1. trigger the is typing event

2. listen to `onUserStoppedTyping`

**Comment by klemenk161** [comment]
Hi, similar issue. UserStoppedTyping only triggers one time(first time the user stops typing) in an established connection. UserStartedTyping works as expected every time for every room.

```kotlin
when(event) {
    is RoomSubscriptionEvent.UserStartedTyping -> {
        if(event.user.id != currentUser.id)
            typingData.value = true
    }
    is RoomSubscriptionEvent.UserStoppedTyping -> {
        if(event.user.id != currentUser.id)
            typingData.value = false
    }
```

**Comment by daniellevass** [comment]
Hi, closing this issue as there has not been any activity in some time. If this is still an issue please contact support@pusher.com, and they can give you more direct help 🙂
