### ISSUE TITLE
Strange use of data class

### ISSUE THREAD

**Issue by nbransby** [pusher/chatkit-android#61]
https://github.com/pusher/chatkit-android/blob/185fa8ca0b405c899a8c9c35acf755449f3205aa/chatkit-core/src/main/kotlin/com/pusher/chatkit/ChatManagerEvents.kt#L12

This feels like an interface so why is it a data class?

**Comment by daniellevass** [comment]
Hi, closing this issue as there has not been any activity in some time. If this is still an issue please contact support@pusher.com, and they can give you more direct help 🙂
