### ISSUE TITLE
Room subscription for new message is not working

### ISSUE THREAD

**Issue by gethunt** [pusher/chatkit-android#62]
Hi, 
When I have chat between two clients, I can get only the first new message, after that all other new messages are not coming to the target client,

my code:

```kotlin
   subscription = ChatkitManager.getInstance().getUserManager().subscribeToRoom(roomID, new Function1<RoomSubscriptionEvent, Unit>() {
           @Override
           public Unit invoke(final RoomSubscriptionEvent roomSubscriptionEvent) {

               if(roomSubscriptionEvent instanceof RoomSubscriptionEvent.NewMessage){
                         //handle message
                }
```

**Comment by gethunt** [comment]
No issue solved. 
thanks

**Comment by Mostafa-MA-Saleh** [comment]
I have the same problem.
@gethunt If you don't mind could you elaborate on how you actually got the issue fixed, that would be much appreciated!
