### ISSUE TITLE
Issue with adding chatkit dependecy to gradle 

### ISSUE THREAD

**Issue by chrisjnr** [pusher/chatkit-android#76]
i add the dependency as explained in the ReadMe
my gradle keeps crashing and i keep getting the same errors
it seems to search everywhere including the maven repositories but cant find the files

Error:Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find com.pusher:chatkit-android:$chatkit-version.
  Searched in the following locations:
      file:/opt/google/android-sdk/extras/m2repository/com/pusher/chatkit-android/$chatkit-version/chatkit-android-$chatkit-version.pom
      file:/opt/google/android-sdk/extras/m2repository/com/pusher/chatkit-android/$chatkit-version/chatkit-android-$chatkit-version.jar
      file:/opt/google/android-sdk/extras/google/m2repository/com/pusher/chatkit-android/$chatkit-version/chatkit-android-$chatkit-version.pom
      file:/opt/google/android-sdk/extras/google/m2repository/com/pusher/chatkit-android/$chatkit-version/chatkit-android-$chatkit-version.jar
      file:/opt/google/android-sdk/extras/android/m2repository/com/pusher/chatkit-android/$chatkit-version/chatkit-android-$chatkit-version.pom
      file:/opt/google/android-sdk/extras/android/m2repository/com/pusher/chatkit-android/$chatkit-version/chatkit-android-$chatkit-version.jar
      file:/opt/google/android-studio/gradle/m2repository/com/pusher/chatkit-android/$chatkit-version/chatkit-android-$chatkit-version.pom
      file:/opt/google/android-studio/gradle/m2repository/com/pusher/chatkit-android/$chatkit-version/chatkit-android-$chatkit-version.jar
      https://dl.google.com/dl/android/maven2/com/pusher/chatkit-android/$chatkit-version/chatkit-android-$chatkit-version.pom
      https://dl.google.com/dl/android/maven2/com/pusher/chatkit-android/$chatkit-version/chatkit-android-$chatkit-version.jar
      https://jcenter.bintray.com/com/pusher/chatkit-android/$chatkit-version/chatkit-android-$chatkit-version.pom
      https://jcenter.bintray.com/com/pusher/chatkit-android/$chatkit-version/chatkit-android-$chatkit-version.jar
  Required by:
      project :app

These are my dependencies:
dependencies {
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.android.support:support-v4:27.1.1'
    compile 'com.android.support:gridlayout-v7:27.1.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    compile 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    compile 'com.android.support:design:27.1.1'
    compile 'com.android.support:cardview-v7:27.1.1'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.google.code.gson:gson:2.8.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'org.apache.httpcomponents:httpclient-android:4.3.5.1'
    implementation 'com.pusher:chatkit-android:$chatkit-version'
}

**Comment by KingIdee** [comment]
Did you declare the `$chatkit-version` variable anywhere in your app-module or project `build.gradle` file ?

**Comment by chrisjnr** [comment]
Thanks, I didn't at the time but instead I've substituted the most recent version which is 0.2.4 for the $chatkit-version, I just corrected it now. Much appreciated

**Comment by daniellevass** [comment]
Hi, closing this issue as it looks like the original posted issue has been resolved. If this is still an issue please contact support@pusher.com, and they can give you more direct help 🙂
