### ISSUE TITLE
CurrentUser.avatarURL wrong deserialize

### ISSUE THREAD

**Issue by Eddie980** [pusher/chatkit-android#82]
Hello. I use ChatManager.connect() method to recieve CurrentUser, but his avatarUrl always null.  I checked server's response, and server returns correct json with avatarUrl. At class BaseSubscription after this 
`private val ResponseBody.messages: Sequence<Result<SubscriptionMessage<A>, Error>>
        get() = charStream().buffered().lineSequence()
            .map {line -> line.toSubscriptionMessage(messageParser) }`
avatarUrl are lost.

**Comment by mdpye** [comment]
Hi @Eddie980. Fixed in v1.0.3, which should be on jcenter repo any second now.

Thanks for the detailed report.
