### ISSUE TITLE
usersForRoom returning no users on a room with 2 users

### ISSUE THREAD

**Issue by EFCniux** [pusher/chatkit-android#88]
After upgrading from 0.2.4 to 1.0.x (tried with both 1.0.3 and 1.0.5), `currentUser.usersForRoom` does not return any users, even though pusher's dashboard clearly says there are 2 users on the requested room.

Sample code:
Working -> [v.0.2.4.txt](https://github.com/pusher/chatkit-android/files/2619265/v.0.2.4.txt)
Not Working ->  [v1.0.x.txt](https://github.com/pusher/chatkit-android/files/2619266/v1.0.x.txt)

**Comment by llKoull** [comment]
Hi!

I'm experiencing the same issue here 😟

Is there any solution?

Thanks and best regards!

**Comment by mrkidjordje** [comment]
I've noticed that if you subscribe to a room and after that ask for members you'll get correct data. But still, currentUser without room subscription is not returning rooms with members.

**Comment by EFCniux** [comment]
Subscribing to the room does indeed solve the issue, but this not the documented behavior as per https://docs.pusher.com/chatkit/reference/android#user-properties.

Will use the workaround on the meantime.

**Comment by EFCniux** [comment]
I understand what you mean, but shouldn't that be what `currentUser.usersForRoom` is internally doing on each request? Otherwise what is the point of having said method?

**Comment by iqbalza** [comment]
Any update on this? This is such a simple feature yet not being fixed.

**Comment by Ebraheemb** [comment]
any update here ?

**Comment by daniellevass** [comment]
Hi, We added the feature to get usersForRoom without subscribing to the room in [1.9.0](https://github.com/pusher/chatkit-android/releases/tag/1.9.0). Closing this issue out. If this is still an issue please contact support@pusher.com, and they can give you more direct help 🙂
