### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by amanzan** [pusher/chatkit-android#99]
Cloned the repo and it doesn't even build. I get this error:
Gradle sync failed: 'Gradle: net.bytebuddy:byte-buddy-agent:1.7.4@jar' already disposed

Any help fixing it? Thanks!

**Comment by daniellevass** [comment]
Hi, closing this issue as there has not been any activity in some time. If this is still an issue please contact support@pusher.com, and they can give you more direct help 🙂
